# Generated by Django 3.0 on 2020-02-07 13:04

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='class', max_length=50),
        ),
        migrations.AddField(
            model_name='classroom',
            name='uniqueCode',
            field=models.CharField(default=classroom.models.Classroom.generateUniqueCode, max_length=50),
        ),
    ]
