# Generated by Django 3.0 on 2020-02-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200207_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='class', max_length=50, unique=True),
        ),
    ]
