# Generated by Django 3.0 on 2020-02-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_classroom_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='class', max_length=50),
        ),
    ]
