# Generated by Django 3.0 on 2020-02-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questino',
        ),
    ]
