version: '3'

services:
  db-dev:
    image: postgres
    container_name: db-dev
    environment:
      POSTGRES_DB: Moodle
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
  web-dev:
    container_name: api-web
    build: .
    command:  bash -c "python manage.py makemigrations
      && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    depends_on:
      - db-dev